
services:
  api:
    build: .
    ports:
      - "9000:9000"
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - GIN_MODE=release
      - TWITCH_GO_BACKEND_ENV=prod