name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - name: Run the tests
      run: go test ./...

  deploy:
    runs-on: self-hosted

    needs: [ test ]

    steps:
    - uses: actions/checkout@v2
    - name: Deploy on self-hosted
      env:
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
      run: docker-compose up -d
