name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - name: Run the tests
      run: go test ./...

  deploy:
    runs-on: self-hosted

    needs: [ test ]

    steps:
    - uses: actions/checkout@v2
    - name: Deploy on self-hosted
      env:
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: |
        docker-compose down
        docker-compose up -d --build
